# Generated by Django 3.1.7 on 2021-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'directors',
                'ordering': ['uid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(blank=True, max_length=500, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('release_date', models.TextField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('director_id', models.IntegerField()),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
