# Generated by Django 3.2.3 on 2021-05-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_auto_20210522_0429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
